---
title: ''
output: pdf_document
---

# Conclusions

My analysis revealed complex relationships of biodiversity change and large-scale human activities across taxa with a decrease of 1.6% of temporal turnover for every 10% increase in accessibility. These findings challenge the assumption that the absence of large-scale human activity is sufficient to conserve compositional biodiversity (Di Marco et al., 2019). I support the latest research, calling for the importance of using real-world data to detect longer term dynamics that are revealing more complex biodiversity changes (Daskalova et al., 2019). I further highlighted the additional complexity in biodiversity changes arising through interactions between different drivers and environmental changes. To fully comprehend biodiversity changes it is not sufficient to consider singular environmental changes in isolation. More differentiated research that distinguishes the relative contributions of each driver is needed, as a metric like accessibility, albeit useful in one sense, is too simplistic. My findings highlight the complexity of biodiversity change as well as the heterogeneity in responses. Consequently, I am challenging calls for establishing wilderness areas (Di Marco et al., 2019) as a conservation priority, unless we gain a better understanding of biodiversity changes both inside and outside of human-impacted areas. Being able to adequately quantify wide ranging responses of biodiversity change to large-scale human activities will improve predictions for better international policy making in the light of our rapidly changing Anthropocene.