---
title: ''
output: pdf_document
---

# Discussion

## Overview
My global analysis of 5787 terrestrial time-series demonstrates complex heterogeneity in the relationships between large-scale human activity and biodiversity changes. Contrary to my predictions, I revealed that as accessibility increases, temporal turnover declined (Figure 3), suggesting a rejection of my alternative hypothesis of a positive relationship. This highlights the importance of analysing multiple drivers and its interacting effects on biodiversity change. Simultaneously, I demonstrated that even the lower range of predicted temporal turnover rates are above baseline levels, highlighting widespread temporal turnover across levels of human activity (Figure 3). I found a very similar baseline magnitude of temporal turnover across levels of human population density, although in this case without any directional trend (Figure 4), pointing towards the importance of capturing both direct and indirect effects of human activities. I uncovered distinct taxonomic signals of temporal turnover, with terrestrial invertebrates experiencing the highest amount, followed by mammals, whereas plants and birds showed relatively lower levels of turnover (Figure 5). The lack of sufficient data prevented me to answer my original questions of an interaction between accessibility and human population.  Similarly, I could not quantify the relationship between temporal turnover and taxa across levels of accessibility which highlights the need for more comprehensive sampling in the future. On a global scale, human activities are causing a decline in biodiversity, but considering a more local scale, I uncovered heterogenous responses to large-scale anthropogenic activity challenging the assumption that the absence of human activity is sufficient to conserve compositional biodiversity.

Global datasets have been criticised for various reasons with important implications for the interpretation of results. The first criticism concerns global biodiversity datasets often spatially underrepresenting areas modified by human activities (Gonzalez et al., 2016). This prevents an accurate reflection of relationships between human modification and environmental changes. I found that locations of biodiversity monitoring in my data covered a representative range of accessibility scores, as many parts of our planet are highly accessible (see Figure 8 in appendix B). My data suffered from the opposite, as it underrepresented areas with low accessibility, causing high uncertainty of the model at low levels (Figure 3). Additionally, 33% of the time-series monitored fell into protected areas while having an accessibility level of 0.9 and above (see Figure 11 in appendix B). This indicates that turnover rates at high levels of accessibility might have been influenced by the presence of protected areas which are not strictly representative of other highly accessible areas. In a post-hoc sensitivity analysis, I used a subset of plants-only data because it showed the most variation across levels of accessibility (see Figure 10 in appendix B). I found similar directional relationships between accessibility and turnover (see Figure 7 in appendix A), as well as relatively high coincidence of time-series in protected areas (39%). Model convergence could not be achieved with a subset of data excluding protected areas, making it difficult to exclude this potential influence on turnover. The second criticism concerns mismatches in timing of disturbance and monitored time-series, as only then an attribution of a global change driver to biodiversity change is possible (Gonzalez et al., 2016; De Palma et al., 2018). One robust method to do this is the Before-After-Control-Impact (BACI) method, which compares changes before and after disturbance. In my case, human activities related to accessibility have often occurred before the start of the biodiversity monitoring (Ibisch et al., 2016), nor did I have a quantification of large-scale human activities over time which prevented me from doing a BACI. Therefore, my results can be interpreted as the time-accumulated impact of human activities which captured both disturbances and recoveries at the same time and therefore also represented the real world (Vellend, Dornelas, et al., 2017). While biodiversity changes and their attribution to large-scale human activities is somewhat limited with my method, I still observed an accurate picture of the cumulative and interactive responses captured across levels of accessibility corresponded with human transformations of the natural environment.

## Temporal turnover and accessibility (Research Question 1)
Contrary to my first prediction, I found that temporal turnover decreased as accessibility increases (Figure 3). I also found that 63% of all time-series monitored showed some degree of turnover (turnover > zero). Furthermore, the lowest model prediction at the highest level of accessibility pointed towards 25% species replacement across the monitored time periods (Figure 3), which is higher than hypothetical baseline turnover rates (Dornelas et al., 2014), indicating widespread turnover rates across levels of accessibility. The negative relationship observed could be due to various reasons. Firstly, heterogeneity exists in species’ responses to impacts caused by human activities as it is also reflected in the ongoing debate about habitat fragmentation (Fahrig, 2017; Damschen et al., 2019). Secondly, potential interactions of multiple drivers play an important role. Simultaneous drivers can relate to each other in different ways, being either additive, antagonist or amplified (Côté, Darling and Brown, 2016; Sirami et al., 2017). Research on multiple drivers and their interactions has been limited (Sirami et al., 2017; Mazor et al., 2018) with previous biodiversity change research mostly focussed on single drivers of environmental change such as forest loss (Daskalova et al., 2019), land use change (Newbold et al., 2015) or warming (Spooner, Pearson and Freeman, 2018). A marine study has found antagonistic effects of multiple drivers on biodiversity changes resulting in no net biodiversity change (Dunic et al., 2017). Accessibility is a cumulative variable, representing many different drivers and their respective environmental impacts. Most research has focussed only on a singular impact of accessibility so far. Land-use change, urbanisation and roads are associated with both higher rates of extinction, due to increased resource and habitat constraints and immigration due to increased alien potential (Hulme, 2009; Seebens et al., 2018). We currently only have a limited understanding how the magnitude of exposure to these drivers differ, which is likely to also influence biodiversity change observed. However, many of the impacts described co-occur and can affect the intensity and interaction of one another (Geary et al., 2019). Furthermore, other drivers such as climate change can bring additional complexity in patterns of exposure, as these drivers can cooccur and interact with human activity-related drivers as well (Chazal and Rounsevell, 2009; Gonzalez et al., 2016). One determining coincidence of my study could be that the very inaccessible places I studied coincide with areas that are in very high and low latitudes, which are often sensitive to climate change (Myers-Smith et al., 2019) and thus might show a higher level of turnover. My findings highlight that accounting for multiple drivers and potential interactions is essential when attributing biodiversity change.

## Temporal turnover and human population density (Research question 2 modified)
I found a very similar baseline magnitude of temporal turnover and human population density as with accessibility, although in this case without any directional trend. The lowest model prediction at the highest level of human population density pointed towards a turnover level of 22% across the monitored time periods (Figure 4), making it very similar to that of accessibility (24%) (Figure 3), confirming a generally increased turnover rate above natural baseline levels. Interestingly, when looking at the coincidence of the distribution of accessibility and human population density, they were located on opposite ends (see Figure 9 in appendix B). That indicates that high accessibility does not coincide with high human population density, but many places on earth have been modified even without the immediate or dense presence of humans. This is further emphasized by the finding that many highly accessible places coincide with protected areas (see Figure 11 in appendix B). Therefore, accessibility seems to be an important measure that can also capture indirect impacts. Much of our planet has been altered in such a way that patches of habitat are exposed to both direct and indirect influences of human activity. While land-use change from pristine to urban centres and agriculture and forest loss represent more direct impacts, neighbouring habitats fragments are also impacted indirectly and this might be reflected in a metric such as accessibility (Haddad et al., 2015). As pointed out by Gonzalez et al. (2016), understanding and contrasting both direct and indirect effects of human activity on biodiversity change is a challenge that has not been addressed adequately yet. My findings highlight the importance of capturing both direct and indirect effects of human activities when attributing biodiversity change to global change drivers.

## Temporal turnover and taxa (Research Question 3 modified)
My findings highlight variation of temporal turnover among taxa, with terrestrial invertebrates experiencing the highest amount, followed by mammals, whereas plants and birds showed relatively lower levels of turnover (Figure 5). Invertebrates’ relationship should be treated carefully, as the number of sampling was disproportionally lower for time series-studied (6%) and coincidence with potential confounding protected areas (4%), as well as known difficulties in sampling invertebrates (Andersen et al., 2004). Species’ responses ultimately depend on their traits such as life history traits, generation time, trophic levels and reproduction strategy (Purvis et al., 2000). Concerning species’ vulnerability to human impacts and consequently setting conservation priorities, research often focussed on traits such as mobility and specialisation. While some research has found more persistence of more mobile species and of species that are more generalist in human impacted areas (Newbold et al., 2014), other research has found both populations increases, and declines related to range size and specialisation (Daskalova, Myers-Smith and Godlee, 2019). However, both studies did not consider community composition in their analysis. I did not find a relationship between the turnover and mobility, assuming birds to be more-mobile and plants to be less-mobile species. Despite there being no relationship with traits in this study, phylogenetic relatedness might predict extinction over longer timescales (Jetz and Pyron, 2018). Shorter timescales might be influenced by other processes such as the interaction of effects and ecological lags. I demonstrated heterogenous levels of turnover experienced among taxa, pointing out the need to quantify how these relationships are moderated by species’ traits and vulnerabilities in order to effectively target conservation efforts.

## Study Limitations
Analyses of biodiversity change can be limited by insufficient and imbalanced taxonomic, spatial and temporal data. The lack of model convergence which prevented answering two of my original research questions, highlighted the need to collect data more comprehensively. Tropical locations and thus species were underrepresented in the biodiversity dataset (see figure 2), as were invertebrates in my subset of data. Spatial scales that are of species-specific relevance can differ heavily among species but also in relation to human impact. In a sensitivity analysis I found that turnover trends only differed in their magnitude but not in the direction of the relationship with accessibility and only between very small scales (1km²) but not across bigger scales (see Figure 6 in appendix A). Lastly, temporal mismatches and missing accurate accounts of past human activities make the attribution of biodiversity change challenging. Recognising heterogenous effects including disturbance and recovery of human impacts and focussing on understanding the interaction of current impacts are thus gaining even more importance. Analysis of biodiversity change and its global change driver can benefit from more comprehensive taxonomic, spatial and temporal data collection of environmental impact and biodiversity data.

## Future directions
Biodiversity change and attributing global change drivers associated with human activities requires a step beyond previous studies which have focussed on singular drivers. Exploring patterns of exposure of multiple influences (Bowler et al., 2020) will give us a more differentiated view than a singular cumulative metric can give. Analysing interactive and cumulative effects of those various drivers, will allow us to better understand the complex varieties with which our activities alter the environment and consequently ecological communities. Understanding the role better that species’ traits play in determining vulnerability to multiple human impacts will lead to more targeted conservation efforts. Also going beyond one singular community, we need to understand better how large-scale reorganization is unfolding across communities as well and how biotic homogenization (Eriksson and Hillebrand, 2019) is influencing ecosystem functioning across scales. Analysing biodiversity change related to multiple drivers across both terrestrial and marine realms will allow development of better conservation strategies.